export const sample_foods = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 4500,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      imageUrlTags: "/icons/dominos.png",
      tags: ['Dominos'],
    },
    {
      id: '2',
      name: 'Meatball',
      price: 3000,
      cookTime: '20-30',
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 5,
      imageUrl: 'food-2.jpg',
      imageUrlTags: "/icons/chinese.jpg",
      tags: ['Chicken Republic', 'The Place'],
    },
    {
      id: '3',
      name: 'Hamburger',
      price: 2500,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'food-3.jpg',
      tags: ['Mr Biggs'],
    },
    {
      id: '4',
      name: 'Fried Potatoes',
      price: 600,
      cookTime: '15-20',
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 3,
      imageUrl: 'food-4.jpg',
      imageUrlTags: "/icons/placebo.png",
      tags: ['Placebo'],
    },
    {
      id: '5',
      name: 'Chicken Soup',
      price: 1900,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: 'food-5.jpg',
      imageUrlTags: "/icons/chinese.jpg",
      tags: ['Upscale Restaurant', 'Chinese Restaurant'],
    },
    {
      id: '6',
      name: 'Vegetables Pizza',
      price: 4000,
      cookTime: '40-50',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'food-6.jpg',
      imageUrlTags: "/icons/dominos.png",
      tags: ['Dominos'],
    },
  ];
  

  export const sample_tags = [
    { name: 'All', count: 6, imageUrlTags: 'all.jpg', },
    { name: 'Chicken Republic', count: 4, imageUrlTags: '/icons/chicken.png', },
    { name: 'Dominos', count: 2, imageUrlTags: '/icons/dominos.png', },
    { name: 'The Place', count: 3, imageUrlTags: '/icons/place.png', },
    { name: 'Placebo', count: 2, imageUrlTags: '/icons/placebo.png', },
    { name: 'Mr Biggs', count: 1, imageUrlTags: '/icons/biggs.png',},
    { name: 'Chinese Restaurant', count: 1, imageUrlTags: '/icons/chinese.jpg',},
    { name: 'Upscale Restaurant', count: 1, imageUrlTags: '/icons/taste.png'},
  ];
  
  
  export const sample_users = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john@gmail.com',
      password: '12345',
      address: 'Toronto On',
      isAdmin: false,
    },
    {
      id: 2,
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '12345',
      address: 'Shanghai',
      isAdmin: true,
    },
  ];